### ISSUE TITLE
Make dataset available via the Hugging Face Hub

### ISSUE THREAD

**Issue by davanstrien** [C4AI/Pira#1]
This is a really interesting/valuable dataset! It would be awesome to also expose it via the Hugging Face datasets hub (https://huggingface.co/datasets). Since the data is already in a CSV format it should be very easy to do this using the instructions in the [docs](https://huggingface.co/docs/datasets/upload_dataset#upload-dataset) but feel free to ping me if you are interested in doing this and want some support :)

**Comment by paulopirozelli** [comment]
Hi @davanstrien, thank you for the interest in our dataset! We have uploaded it to the Hugging Face datasets hub as you suggested [(https://huggingface.co/datasets/paulopirozelli/pira)](https://huggingface.co/datasets/paulopirozelli/pira). We've also put a link to it on our Github page. We've made all dataset versions available.

If you have any further suggestions, please don't hesitate to reach out!

**Comment by davanstrien** [comment]
@paulopirozelli awesome! Thanks for doing that. Really nice to see more datasets like this :)
